#5596 Refactors
ChainSafe/web3.js-plugin-chainlink pull request #5
Opened 2022-11-09 21:11 UTC by spacesailor24

This PR includes the code changes mentioned in my comment [here](https://github.com/web3/web3.js/issues/5596#issuecomment-1309368030)

### What This PR Does

- Renames `src/reexported_web3_objects.ts` to `src/reexported_web3_context.ts`
    - This file only re-exports `Web3Context` now
- Updates module augmentation done in `src/chainlink_plugin.ts` to only augment `Web3Context`
- Updates Web3 module imports for the test

2022-11-10 08:16 UTC, Muhammad-Altabba requested changes
This is good to augment only `Web3Context`.

However, did you try to use the plugin in a sample project? When I used this MR there is no intellisense for `.chainlink`.
![image](https://user-images.githubusercontent.com/24407834/201035682-e827d181-38ea-4304-bae4-487fa6b25627.png)

So, I suggested the modifications in the comments below, in order to keep the following working:
![image](https://user-images.githubusercontent.com/24407834/201033414-b881023c-34f5-471a-a0cd-5f92cdbb409a.png)

2022-11-10 17:23 UTC, spacesailor24 commented
@Muhammad-Altabba  No I didn't test in a sample project, thank you for catching this!

I added the `export { Web3Context };` you suggested and used the plugin in a sample project, and it seems to work as expected

![image](https://user-images.githubusercontent.com/20375610/201163772-8fe988e2-4152-4cf2-9e89-736297481758.png)

2022-11-10 18:43 UTC, Muhammad-Altabba approved these changes

2022-11-11 00:35 UTC, luu-alex approved these changes

2022-11-11 23:11 UTC, avkos approved these changes

2022-11-11 23:25 UTC, merged